# Disable JDBC auto-configuration to avoid dialect conflict
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.data.jdbc.DataJdbcRepositoriesAutoConfiguration
# Hibernate dialect for SQLite
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.application.name=mcp
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false


# SQLite datasource
spring.datasource.url=jdbc:sqlite:./data/database.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.username=
spring.datasource.password= 

#mcp server
server.port=8181

spring.ai.mcp.server.name=mcp-inventory-management
spring.ai.mcp.server.version=0.0.1
spring.ai.mcp.server.description=MCP server for Inventory Management System

spring.ai.mcp.server.type=sync
spring.ai.mcp.server.protocol=streamable
spring.ai.mcp.server.stdio.enabled=false
spring.ai.mcp.server.request-timeout=30s
spring.ai.mcp.server.annotation-scanner.enabled=true

spring.ai.mcp.server.capabilities.tool=true
spring.ai.mcp.server.capabilities.resource=false
spring.ai.mcp.server.capabilities.prompt=false
spring.ai.mcp.server.capabilities.completion=false

